// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyAL1vNmtXIRpdUQ8nlggWwLdF6CooQJlVI',
    appId: '1:862012628855:web:f9b32d7aa4aa2bad818b72',
    messagingSenderId: '862012628855',
    projectId: 'joie-driver-matrix',
    authDomain: 'joie-driver-matrix.firebaseapp.com',
    storageBucket: 'joie-driver-matrix.appspot.com',
    measurementId: 'G-DSMDRSSRY2',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyC0JGEUKTi1Or_pivr1UhwGxCBW3fKtRAw',
    appId: '1:862012628855:android:6f80d7eaf491bb8a818b72',
    messagingSenderId: '862012628855',
    projectId: 'joie-driver-matrix',
    storageBucket: 'joie-driver-matrix.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDFvKUlKIeucChEyWpL-SvsqiNOK69lJZ4',
    appId: '1:862012628855:ios:ae8b6baafc96d0a9818b72',
    messagingSenderId: '862012628855',
    projectId: 'joie-driver-matrix',
    storageBucket: 'joie-driver-matrix.appspot.com',
    iosClientId: '862012628855-uu5bf1kp4r9u8h6drjsgn15t3frq7i2p.apps.googleusercontent.com',
    iosBundleId: 'com.ciddras.joiedriver',
  );
}
